package ctrmap.pokescript.ide.autocomplete.gui;

import ctrmap.pokescript.ide.autocomplete.nodes.AbstractNode;
import ctrmap.pokescript.ide.autocomplete.nodes.MemberNode;

public class ACDocWindow extends javax.swing.JWindow {

	/**
	 * Creates new form ACDocWindow
	 */
	public ACDocWindow() {
		initComponents();
		docSP.getVerticalScrollBar().setUnitIncrement(16);
	}

	private String doc = null;

	public void buildDoc(AbstractNode selectedNode) {
		if (selectedNode != null && selectedNode instanceof MemberNode) {
			doc = DocumentationHTMLFactory.createDocHTML(((MemberNode) selectedNode).member);
		} else {
			doc = null;
		}
		docLabel.setText(doc);
	}

	public void wOpen() {
		if (doc != null) {
			setSize(550,
					Math.min(400, Math.max(200, docLabel.getPreferredSize().height + docSP.getHorizontalScrollBar().getHeight() + 10)));
			
			setVisible(true);
		} else {
			wClose();
		}
	}

	public void wClose() {
		setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        docSP = new javax.swing.JScrollPane();
        docLabel = new javax.swing.JLabel();

        docLabel.setBackground(new java.awt.Color(255, 255, 255));
        docLabel.setText(null);
        docLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        docLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        docLabel.setOpaque(true);
        docSP.setViewportView(docLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(docSP, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(docSP, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel docLabel;
    private javax.swing.JScrollPane docSP;
    // End of variables declaration//GEN-END:variables

}
