package ctrmap.pokescript.ide.forms;

import ctrmap.pokescript.ide.system.savedata.IDEWorkspace;
import ctrmap.stdlib.fs.accessors.DiskFile;
import ctrmap.stdlib.gui.DialogUtils;
import ctrmap.stdlib.gui.file.CMFileDialog;
import java.io.File;

public class InitialLaunchDialog extends javax.swing.JDialog {

	private IDEWorkspace ws;
	private IDEWorkspace result;

	public InitialLaunchDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		setLocationRelativeTo(parent);
	}

	private void trySetWS(IDEWorkspace ws) {
		if (ws != null) {
			this.ws = ws;
			selectedWorkspace.setText(ws.getRoot().getPath());
			btnContinue.setEnabled(true);
		}
	}
	
	public IDEWorkspace getResult(){
		return result;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        headingLabel = new javax.swing.JLabel();
        selectWorkspaceMsg = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnCreateWorkspace = new javax.swing.JButton();
        btnFindWorkspace = new javax.swing.JButton();
        selectedWorkspaceLabel = new javax.swing.JLabel();
        selectedWorkspace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headingLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(51, 51, 51));
        headingLabel.setText("Welcome!");

        selectWorkspaceMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectWorkspaceMsg.setText("Please select a workspace to begin");

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnContinue.setText("Continue");
        btnContinue.setEnabled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        btnCreateWorkspace.setText("Create a workspace");
        btnCreateWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWorkspaceActionPerformed(evt);
            }
        });

        btnFindWorkspace.setText("Use existing workspace");
        btnFindWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindWorkspaceActionPerformed(evt);
            }
        });

        selectedWorkspaceLabel.setText("Selected workspace: ");

        selectedWorkspace.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectWorkspaceMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectedWorkspaceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectedWorkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateWorkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnFindWorkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectWorkspaceMsg)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateWorkspace)
                    .addComponent(btnFindWorkspace))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedWorkspaceLabel)
                    .addComponent(selectedWorkspace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuit)
                    .addComponent(btnContinue))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
		System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnCreateWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWorkspaceActionPerformed
		WorkspaceCreationDialog dlg = new WorkspaceCreationDialog(this, true);
		dlg.setVisible(true);
		setVisible(true);
		trySetWS(dlg.getResult());
    }//GEN-LAST:event_btnCreateWorkspaceActionPerformed

    private void btnFindWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindWorkspaceActionPerformed
		File dir = CMFileDialog.openDirectoryDialog();

		if (dir != null) {
			IDEWorkspace ws = IDEWorkspace.openWorkspaceIfApplicable(new DiskFile(dir));
			if (ws != null) {
				trySetWS(ws);
			} else {
				DialogUtils.showErrorMessage(this, "Not a workspace", "This directory is not a valid PokéScript workspace (.ide directory not present).");
			}
		}
    }//GEN-LAST:event_btnFindWorkspaceActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
		result = ws;
		dispose();
    }//GEN-LAST:event_btnContinueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnCreateWorkspace;
    private javax.swing.JButton btnFindWorkspace;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel selectWorkspaceMsg;
    private javax.swing.JLabel selectedWorkspace;
    private javax.swing.JLabel selectedWorkspaceLabel;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
